version: '2'

services:
  wsd:
    build: .
    environment:
      NEWRELIC_LICENSE_KEY: ${NEWRELIC_LICENSE_KEY}
      JWT_SECRET: ${INTERPALS_JWT_SECRET}
      REDIS_ADDR: ${INTERPALS_REDIS_PUBSUB_ADDR}
      DB_URI: ${INTERPALS_DB_ADDR}
    ports:
      - "8484:8484"
    network_mode: host
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
