[template]

# The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src   = "websocketerd.tmpl"

# The location to place the rendered configuration file
dest  = "/etc/interpals/websocketerd.json"
